const fs = require('fs');
const assert = require('assert');
const path = require('path');
const root = path.resolve(__dirname, '..');
const main = fs.readFileSync(path.join(root,'app/src/main/java/com/studiokinematics/oryn/MainActivity.java'),'utf8');
const boot = fs.readFileSync(path.join(root,'app/src/main/assets/www/offline/oryn-mobile-bootstrap.js'),'utf8');
const machine = fs.readFileSync(path.join(root,'app/src/main/assets/www/static/custom/oryn-universal-machine-profile-v7.js'),'utf8');
const core = fs.readFileSync(path.join(root,'app/src/main/assets/www/assets/index-D3rZVjEB.js'),'utf8');
assert(main.includes('http://oryn.local:8080'));
assert(main.includes('NetworkInterface.getNetworkInterfaces()'));
assert(main.includes('isPrivateIPv4(ip)'));
assert(main.includes('for (int i=1;i<=254;i++)'));
assert(main.includes('startDiscoveryAsync'));
assert(boot.includes('TMC2208:[2,4,8,16]'));
assert(!boot.includes('TMC2208:[1,2,4,8,16,32,64,128,256]'));
assert(machine.includes('TMC2208:[2,4,8,16]'));
assert(machine.includes('previous no-jumper A4988'));
assert(core.includes('TMC2208 standalone: MS1=LOW + MS2=LOW is 1/8'));
assert(boot.includes('DIRECT_PATTERN_ORIENTATION_KEY'));
console.log('PASS Pi TMC2208 + phone-hotspot Android sync');
