plugins { id 'com.android.application' }

android {
    namespace 'com.studiokinematics.oryn'
    compileSdk 35

    defaultConfig {
        applicationId 'com.studiokinematics.oryn'
        minSdk 26
        targetSdk 35
        versionCode 1040104
        versionName '10.4.1-mobile4-pd-safearea1'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
